models:
  - type: main
    engine: groq
    model: openai/gpt-oss-20b
    api_key_env_var: GROQ_API_KEY

rails:
  input:
    flows:
      - self check input

  output:
    flows:
      - self check output
